//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;

#nullable enable

namespace UnitsNet.NumberExtensions.NumberToLength
{
    /// <summary>
    /// A number to Length Extensions
    /// </summary>
    public static class NumberToLengthExtensions
    {
        /// <inheritdoc cref="Length.FromAstronomicalUnits(UnitsNet.QuantityValue)" />
        public static Length AstronomicalUnits<T>(this T value) =>
            Length.FromAstronomicalUnits(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromCentimeters(UnitsNet.QuantityValue)" />
        public static Length Centimeters<T>(this T value) =>
            Length.FromCentimeters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromDecimeters(UnitsNet.QuantityValue)" />
        public static Length Decimeters<T>(this T value) =>
            Length.FromDecimeters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromDtpPicas(UnitsNet.QuantityValue)" />
        public static Length DtpPicas<T>(this T value) =>
            Length.FromDtpPicas(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromDtpPoints(UnitsNet.QuantityValue)" />
        public static Length DtpPoints<T>(this T value) =>
            Length.FromDtpPoints(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromFathoms(UnitsNet.QuantityValue)" />
        public static Length Fathoms<T>(this T value) =>
            Length.FromFathoms(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromFeet(UnitsNet.QuantityValue)" />
        public static Length Feet<T>(this T value) =>
            Length.FromFeet(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromHands(UnitsNet.QuantityValue)" />
        public static Length Hands<T>(this T value) =>
            Length.FromHands(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromHectometers(UnitsNet.QuantityValue)" />
        public static Length Hectometers<T>(this T value) =>
            Length.FromHectometers(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromChains(UnitsNet.QuantityValue)" />
        public static Length Chains<T>(this T value) =>
            Length.FromChains(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromInches(UnitsNet.QuantityValue)" />
        public static Length Inches<T>(this T value) =>
            Length.FromInches(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromKilolightYears(UnitsNet.QuantityValue)" />
        public static Length KilolightYears<T>(this T value) =>
            Length.FromKilolightYears(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromKilometers(UnitsNet.QuantityValue)" />
        public static Length Kilometers<T>(this T value) =>
            Length.FromKilometers(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromKiloparsecs(UnitsNet.QuantityValue)" />
        public static Length Kiloparsecs<T>(this T value) =>
            Length.FromKiloparsecs(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromLightYears(UnitsNet.QuantityValue)" />
        public static Length LightYears<T>(this T value) =>
            Length.FromLightYears(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromMegalightYears(UnitsNet.QuantityValue)" />
        public static Length MegalightYears<T>(this T value) =>
            Length.FromMegalightYears(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromMegaparsecs(UnitsNet.QuantityValue)" />
        public static Length Megaparsecs<T>(this T value) =>
            Length.FromMegaparsecs(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromMeters(UnitsNet.QuantityValue)" />
        public static Length Meters<T>(this T value) =>
            Length.FromMeters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromMicroinches(UnitsNet.QuantityValue)" />
        public static Length Microinches<T>(this T value) =>
            Length.FromMicroinches(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromMicrometers(UnitsNet.QuantityValue)" />
        public static Length Micrometers<T>(this T value) =>
            Length.FromMicrometers(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromMils(UnitsNet.QuantityValue)" />
        public static Length Mils<T>(this T value) =>
            Length.FromMils(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromMiles(UnitsNet.QuantityValue)" />
        public static Length Miles<T>(this T value) =>
            Length.FromMiles(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromMillimeters(UnitsNet.QuantityValue)" />
        public static Length Millimeters<T>(this T value) =>
            Length.FromMillimeters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromNanometers(UnitsNet.QuantityValue)" />
        public static Length Nanometers<T>(this T value) =>
            Length.FromNanometers(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromNauticalMiles(UnitsNet.QuantityValue)" />
        public static Length NauticalMiles<T>(this T value) =>
            Length.FromNauticalMiles(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromParsecs(UnitsNet.QuantityValue)" />
        public static Length Parsecs<T>(this T value) =>
            Length.FromParsecs(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromPrinterPicas(UnitsNet.QuantityValue)" />
        public static Length PrinterPicas<T>(this T value) =>
            Length.FromPrinterPicas(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromPrinterPoints(UnitsNet.QuantityValue)" />
        public static Length PrinterPoints<T>(this T value) =>
            Length.FromPrinterPoints(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromShackles(UnitsNet.QuantityValue)" />
        public static Length Shackles<T>(this T value) =>
            Length.FromShackles(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromSolarRadiuses(UnitsNet.QuantityValue)" />
        public static Length SolarRadiuses<T>(this T value) =>
            Length.FromSolarRadiuses(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromTwips(UnitsNet.QuantityValue)" />
        public static Length Twips<T>(this T value) =>
            Length.FromTwips(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromUsSurveyFeet(UnitsNet.QuantityValue)" />
        public static Length UsSurveyFeet<T>(this T value) =>
            Length.FromUsSurveyFeet(Convert.ToDecimal(value));

        /// <inheritdoc cref="Length.FromYards(UnitsNet.QuantityValue)" />
        public static Length Yards<T>(this T value) =>
            Length.FromYards(Convert.ToDecimal(value));

    }
}
