//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;

#nullable enable

namespace UnitsNet.NumberExtensions.NumberToVolume
{
    /// <summary>
    /// A number to Volume Extensions
    /// </summary>
    public static class NumberToVolumeExtensions
    {
        /// <inheritdoc cref="Volume.FromAcreFeet(UnitsNet.QuantityValue)" />
        public static Volume AcreFeet<T>(this T value) =>
            Volume.FromAcreFeet(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromAuTablespoons(UnitsNet.QuantityValue)" />
        public static Volume AuTablespoons<T>(this T value) =>
            Volume.FromAuTablespoons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromBoardFeet(UnitsNet.QuantityValue)" />
        public static Volume BoardFeet<T>(this T value) =>
            Volume.FromBoardFeet(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCentiliters(UnitsNet.QuantityValue)" />
        public static Volume Centiliters<T>(this T value) =>
            Volume.FromCentiliters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicCentimeters(UnitsNet.QuantityValue)" />
        public static Volume CubicCentimeters<T>(this T value) =>
            Volume.FromCubicCentimeters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicDecimeters(UnitsNet.QuantityValue)" />
        public static Volume CubicDecimeters<T>(this T value) =>
            Volume.FromCubicDecimeters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicFeet(UnitsNet.QuantityValue)" />
        public static Volume CubicFeet<T>(this T value) =>
            Volume.FromCubicFeet(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicHectometers(UnitsNet.QuantityValue)" />
        public static Volume CubicHectometers<T>(this T value) =>
            Volume.FromCubicHectometers(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicInches(UnitsNet.QuantityValue)" />
        public static Volume CubicInches<T>(this T value) =>
            Volume.FromCubicInches(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicKilometers(UnitsNet.QuantityValue)" />
        public static Volume CubicKilometers<T>(this T value) =>
            Volume.FromCubicKilometers(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicMeters(UnitsNet.QuantityValue)" />
        public static Volume CubicMeters<T>(this T value) =>
            Volume.FromCubicMeters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicMicrometers(UnitsNet.QuantityValue)" />
        public static Volume CubicMicrometers<T>(this T value) =>
            Volume.FromCubicMicrometers(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicMiles(UnitsNet.QuantityValue)" />
        public static Volume CubicMiles<T>(this T value) =>
            Volume.FromCubicMiles(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicMillimeters(UnitsNet.QuantityValue)" />
        public static Volume CubicMillimeters<T>(this T value) =>
            Volume.FromCubicMillimeters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromCubicYards(UnitsNet.QuantityValue)" />
        public static Volume CubicYards<T>(this T value) =>
            Volume.FromCubicYards(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromDecausGallons(UnitsNet.QuantityValue)" />
        public static Volume DecausGallons<T>(this T value) =>
            Volume.FromDecausGallons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromDeciliters(UnitsNet.QuantityValue)" />
        public static Volume Deciliters<T>(this T value) =>
            Volume.FromDeciliters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromDeciusGallons(UnitsNet.QuantityValue)" />
        public static Volume DeciusGallons<T>(this T value) =>
            Volume.FromDeciusGallons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromHectocubicFeet(UnitsNet.QuantityValue)" />
        public static Volume HectocubicFeet<T>(this T value) =>
            Volume.FromHectocubicFeet(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromHectocubicMeters(UnitsNet.QuantityValue)" />
        public static Volume HectocubicMeters<T>(this T value) =>
            Volume.FromHectocubicMeters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromHectoliters(UnitsNet.QuantityValue)" />
        public static Volume Hectoliters<T>(this T value) =>
            Volume.FromHectoliters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromHectousGallons(UnitsNet.QuantityValue)" />
        public static Volume HectousGallons<T>(this T value) =>
            Volume.FromHectousGallons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromImperialBeerBarrels(UnitsNet.QuantityValue)" />
        public static Volume ImperialBeerBarrels<T>(this T value) =>
            Volume.FromImperialBeerBarrels(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromImperialGallons(UnitsNet.QuantityValue)" />
        public static Volume ImperialGallons<T>(this T value) =>
            Volume.FromImperialGallons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromImperialOunces(UnitsNet.QuantityValue)" />
        public static Volume ImperialOunces<T>(this T value) =>
            Volume.FromImperialOunces(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromImperialPints(UnitsNet.QuantityValue)" />
        public static Volume ImperialPints<T>(this T value) =>
            Volume.FromImperialPints(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromKilocubicFeet(UnitsNet.QuantityValue)" />
        public static Volume KilocubicFeet<T>(this T value) =>
            Volume.FromKilocubicFeet(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromKilocubicMeters(UnitsNet.QuantityValue)" />
        public static Volume KilocubicMeters<T>(this T value) =>
            Volume.FromKilocubicMeters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromKiloimperialGallons(UnitsNet.QuantityValue)" />
        public static Volume KiloimperialGallons<T>(this T value) =>
            Volume.FromKiloimperialGallons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromKiloliters(UnitsNet.QuantityValue)" />
        public static Volume Kiloliters<T>(this T value) =>
            Volume.FromKiloliters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromKilousGallons(UnitsNet.QuantityValue)" />
        public static Volume KilousGallons<T>(this T value) =>
            Volume.FromKilousGallons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromLiters(UnitsNet.QuantityValue)" />
        public static Volume Liters<T>(this T value) =>
            Volume.FromLiters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromMegacubicFeet(UnitsNet.QuantityValue)" />
        public static Volume MegacubicFeet<T>(this T value) =>
            Volume.FromMegacubicFeet(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromMegaimperialGallons(UnitsNet.QuantityValue)" />
        public static Volume MegaimperialGallons<T>(this T value) =>
            Volume.FromMegaimperialGallons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromMegaliters(UnitsNet.QuantityValue)" />
        public static Volume Megaliters<T>(this T value) =>
            Volume.FromMegaliters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromMegausGallons(UnitsNet.QuantityValue)" />
        public static Volume MegausGallons<T>(this T value) =>
            Volume.FromMegausGallons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromMetricCups(UnitsNet.QuantityValue)" />
        public static Volume MetricCups<T>(this T value) =>
            Volume.FromMetricCups(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromMetricTeaspoons(UnitsNet.QuantityValue)" />
        public static Volume MetricTeaspoons<T>(this T value) =>
            Volume.FromMetricTeaspoons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromMicroliters(UnitsNet.QuantityValue)" />
        public static Volume Microliters<T>(this T value) =>
            Volume.FromMicroliters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromMilliliters(UnitsNet.QuantityValue)" />
        public static Volume Milliliters<T>(this T value) =>
            Volume.FromMilliliters(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromOilBarrels(UnitsNet.QuantityValue)" />
        public static Volume OilBarrels<T>(this T value) =>
            Volume.FromOilBarrels(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromUkTablespoons(UnitsNet.QuantityValue)" />
        public static Volume UkTablespoons<T>(this T value) =>
            Volume.FromUkTablespoons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromUsBeerBarrels(UnitsNet.QuantityValue)" />
        public static Volume UsBeerBarrels<T>(this T value) =>
            Volume.FromUsBeerBarrels(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromUsCustomaryCups(UnitsNet.QuantityValue)" />
        public static Volume UsCustomaryCups<T>(this T value) =>
            Volume.FromUsCustomaryCups(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromUsGallons(UnitsNet.QuantityValue)" />
        public static Volume UsGallons<T>(this T value) =>
            Volume.FromUsGallons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromUsLegalCups(UnitsNet.QuantityValue)" />
        public static Volume UsLegalCups<T>(this T value) =>
            Volume.FromUsLegalCups(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromUsOunces(UnitsNet.QuantityValue)" />
        public static Volume UsOunces<T>(this T value) =>
            Volume.FromUsOunces(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromUsPints(UnitsNet.QuantityValue)" />
        public static Volume UsPints<T>(this T value) =>
            Volume.FromUsPints(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromUsQuarts(UnitsNet.QuantityValue)" />
        public static Volume UsQuarts<T>(this T value) =>
            Volume.FromUsQuarts(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromUsTablespoons(UnitsNet.QuantityValue)" />
        public static Volume UsTablespoons<T>(this T value) =>
            Volume.FromUsTablespoons(Convert.ToDecimal(value));

        /// <inheritdoc cref="Volume.FromUsTeaspoons(UnitsNet.QuantityValue)" />
        public static Volume UsTeaspoons<T>(this T value) =>
            Volume.FromUsTeaspoons(Convert.ToDecimal(value));

    }
}
