//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Globalization;
using System.Linq;
using JetBrains.Annotations;
using UnitsNet.InternalHelpers;
using UnitsNet.Units;

#nullable enable

// ReSharper disable once CheckNamespace

namespace UnitsNet
{
    /// <inheritdoc />
    /// <summary>
    ///     Mass flow is the ratio of the mass change to the time during which the change occurred (value of mass changes per unit time).
    /// </summary>
    public partial struct MassFlow : IQuantity<MassFlowUnit>, IEquatable<MassFlow>, IComparable, IComparable<MassFlow>, IConvertible, IFormattable
    {
        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        private readonly decimal _value;

        /// <summary>
        ///     The unit this quantity was constructed with.
        /// </summary>
        private readonly MassFlowUnit? _unit;

        static MassFlow()
        {
            BaseDimensions = new BaseDimensions(0, 1, -1, 0, 0, 0, 0);

            Info = new QuantityInfo<MassFlowUnit>(QuantityType.MassFlow,
                new UnitInfo<MassFlowUnit>[] {
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.CentigramPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.CentigramPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.DecagramPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.DecagramPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.DecigramPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.DecigramPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.GramPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.GramPerHour, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.GramPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.HectogramPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.HectogramPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.KilogramPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.KilogramPerHour, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.KilogramPerMinute, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.KilogramPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.MegagramPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.MegapoundPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.MegapoundPerHour, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.MegapoundPerMinute, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.MegapoundPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.MicrogramPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.MicrogramPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.MilligramPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.MilligramPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.NanogramPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.NanogramPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.PoundPerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.PoundPerHour, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.PoundPerMinute, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.PoundPerSecond, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.ShortTonPerHour, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.TonnePerDay, BaseUnits.Undefined),
                    new UnitInfo<MassFlowUnit>(MassFlowUnit.TonnePerHour, BaseUnits.Undefined),
                },
                BaseUnit, Zero, BaseDimensions);
        }

        /// <summary>
        ///     Creates the quantity with the given numeric value and unit.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unit">The unit representation to construct this quantity with.</param>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public MassFlow(decimal value, MassFlowUnit unit)
        {
            if(unit == MassFlowUnit.Undefined)
              throw new ArgumentException("The quantity can not be created with an undefined unit.", nameof(unit));

            _value = value;
            _unit = unit;
        }

        /// <summary>
        /// Creates an instance of the quantity with the given numeric value in units compatible with the given <see cref="UnitSystem"/>.
        /// If multiple compatible units were found, the first match is used.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unitSystem">The unit system to create the quantity with.</param>
        /// <exception cref="ArgumentNullException">The given <see cref="UnitSystem"/> is null.</exception>
        /// <exception cref="ArgumentException">No unit was found for the given <see cref="UnitSystem"/>.</exception>
        public MassFlow(decimal value, UnitSystem unitSystem)
        {
            if(unitSystem is null) throw new ArgumentNullException(nameof(unitSystem));

            var unitInfos = Info.GetUnitInfosFor(unitSystem.BaseUnits);
            var firstUnitInfo = unitInfos.FirstOrDefault();

            _value = value;
            _unit = firstUnitInfo?.Value ?? throw new ArgumentException("No units were found for the given UnitSystem.", nameof(unitSystem));
        }

        #region Static Properties

        /// <inheritdoc cref="IQuantity.QuantityInfo"/>
        public static QuantityInfo<MassFlowUnit> Info { get; }

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public static BaseDimensions BaseDimensions { get; }

        /// <summary>
        ///     The base unit of MassFlow, which is GramPerSecond. All conversions go via this value.
        /// </summary>
        public static MassFlowUnit BaseUnit { get; } = MassFlowUnit.GramPerSecond;

        /// <summary>
        /// Represents the largest possible value of MassFlow
        /// </summary>
        public static MassFlow MaxValue { get; } = new MassFlow(decimal.MaxValue, BaseUnit);

        /// <summary>
        /// Represents the smallest possible value of MassFlow
        /// </summary>
        public static MassFlow MinValue { get; } = new MassFlow(decimal.MinValue, BaseUnit);

        /// <summary>
        ///     The <see cref="QuantityType" /> of this quantity.
        /// </summary>
        public static QuantityType QuantityType { get; } = QuantityType.MassFlow;

        /// <summary>
        ///     All units of measurement for the MassFlow quantity.
        /// </summary>
        public static MassFlowUnit[] Units { get; } = Enum.GetValues(typeof(MassFlowUnit)).Cast<MassFlowUnit>().Except(new MassFlowUnit[]{ MassFlowUnit.Undefined }).ToArray();

        /// <summary>
        ///     Gets an instance of this quantity with a value of 0 in the base unit GramPerSecond.
        /// </summary>
        public static MassFlow Zero { get; } = new MassFlow(0, BaseUnit);

        #endregion

        #region Properties

        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        public decimal Value => _value;

        Enum IQuantity.Unit => Unit;

        /// <inheritdoc />
        public MassFlowUnit Unit => _unit.GetValueOrDefault(BaseUnit);

        /// <inheritdoc />
        public QuantityInfo<MassFlowUnit> QuantityInfo => Info;

        /// <inheritdoc cref="IQuantity.QuantityInfo"/>
        QuantityInfo IQuantity.QuantityInfo => Info;

        /// <summary>
        ///     The <see cref="QuantityType" /> of this quantity.
        /// </summary>
        public QuantityType Type => MassFlow.QuantityType;

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public BaseDimensions Dimensions => MassFlow.BaseDimensions;

        #endregion

        #region Conversion Properties

        /// <summary>
        ///     Get MassFlow in CentigramsPerDay.
        /// </summary>
        public decimal CentigramsPerDay => As(MassFlowUnit.CentigramPerDay);

        /// <summary>
        ///     Get MassFlow in CentigramsPerSecond.
        /// </summary>
        public decimal CentigramsPerSecond => As(MassFlowUnit.CentigramPerSecond);

        /// <summary>
        ///     Get MassFlow in DecagramsPerDay.
        /// </summary>
        public decimal DecagramsPerDay => As(MassFlowUnit.DecagramPerDay);

        /// <summary>
        ///     Get MassFlow in DecagramsPerSecond.
        /// </summary>
        public decimal DecagramsPerSecond => As(MassFlowUnit.DecagramPerSecond);

        /// <summary>
        ///     Get MassFlow in DecigramsPerDay.
        /// </summary>
        public decimal DecigramsPerDay => As(MassFlowUnit.DecigramPerDay);

        /// <summary>
        ///     Get MassFlow in DecigramsPerSecond.
        /// </summary>
        public decimal DecigramsPerSecond => As(MassFlowUnit.DecigramPerSecond);

        /// <summary>
        ///     Get MassFlow in GramsPerDay.
        /// </summary>
        public decimal GramsPerDay => As(MassFlowUnit.GramPerDay);

        /// <summary>
        ///     Get MassFlow in GramsPerHour.
        /// </summary>
        public decimal GramsPerHour => As(MassFlowUnit.GramPerHour);

        /// <summary>
        ///     Get MassFlow in GramsPerSecond.
        /// </summary>
        public decimal GramsPerSecond => As(MassFlowUnit.GramPerSecond);

        /// <summary>
        ///     Get MassFlow in HectogramsPerDay.
        /// </summary>
        public decimal HectogramsPerDay => As(MassFlowUnit.HectogramPerDay);

        /// <summary>
        ///     Get MassFlow in HectogramsPerSecond.
        /// </summary>
        public decimal HectogramsPerSecond => As(MassFlowUnit.HectogramPerSecond);

        /// <summary>
        ///     Get MassFlow in KilogramsPerDay.
        /// </summary>
        public decimal KilogramsPerDay => As(MassFlowUnit.KilogramPerDay);

        /// <summary>
        ///     Get MassFlow in KilogramsPerHour.
        /// </summary>
        public decimal KilogramsPerHour => As(MassFlowUnit.KilogramPerHour);

        /// <summary>
        ///     Get MassFlow in KilogramsPerMinute.
        /// </summary>
        public decimal KilogramsPerMinute => As(MassFlowUnit.KilogramPerMinute);

        /// <summary>
        ///     Get MassFlow in KilogramsPerSecond.
        /// </summary>
        public decimal KilogramsPerSecond => As(MassFlowUnit.KilogramPerSecond);

        /// <summary>
        ///     Get MassFlow in MegagramsPerDay.
        /// </summary>
        public decimal MegagramsPerDay => As(MassFlowUnit.MegagramPerDay);

        /// <summary>
        ///     Get MassFlow in MegapoundsPerDay.
        /// </summary>
        public decimal MegapoundsPerDay => As(MassFlowUnit.MegapoundPerDay);

        /// <summary>
        ///     Get MassFlow in MegapoundsPerHour.
        /// </summary>
        public decimal MegapoundsPerHour => As(MassFlowUnit.MegapoundPerHour);

        /// <summary>
        ///     Get MassFlow in MegapoundsPerMinute.
        /// </summary>
        public decimal MegapoundsPerMinute => As(MassFlowUnit.MegapoundPerMinute);

        /// <summary>
        ///     Get MassFlow in MegapoundsPerSecond.
        /// </summary>
        public decimal MegapoundsPerSecond => As(MassFlowUnit.MegapoundPerSecond);

        /// <summary>
        ///     Get MassFlow in MicrogramsPerDay.
        /// </summary>
        public decimal MicrogramsPerDay => As(MassFlowUnit.MicrogramPerDay);

        /// <summary>
        ///     Get MassFlow in MicrogramsPerSecond.
        /// </summary>
        public decimal MicrogramsPerSecond => As(MassFlowUnit.MicrogramPerSecond);

        /// <summary>
        ///     Get MassFlow in MilligramsPerDay.
        /// </summary>
        public decimal MilligramsPerDay => As(MassFlowUnit.MilligramPerDay);

        /// <summary>
        ///     Get MassFlow in MilligramsPerSecond.
        /// </summary>
        public decimal MilligramsPerSecond => As(MassFlowUnit.MilligramPerSecond);

        /// <summary>
        ///     Get MassFlow in NanogramsPerDay.
        /// </summary>
        public decimal NanogramsPerDay => As(MassFlowUnit.NanogramPerDay);

        /// <summary>
        ///     Get MassFlow in NanogramsPerSecond.
        /// </summary>
        public decimal NanogramsPerSecond => As(MassFlowUnit.NanogramPerSecond);

        /// <summary>
        ///     Get MassFlow in PoundsPerDay.
        /// </summary>
        public decimal PoundsPerDay => As(MassFlowUnit.PoundPerDay);

        /// <summary>
        ///     Get MassFlow in PoundsPerHour.
        /// </summary>
        public decimal PoundsPerHour => As(MassFlowUnit.PoundPerHour);

        /// <summary>
        ///     Get MassFlow in PoundsPerMinute.
        /// </summary>
        public decimal PoundsPerMinute => As(MassFlowUnit.PoundPerMinute);

        /// <summary>
        ///     Get MassFlow in PoundsPerSecond.
        /// </summary>
        public decimal PoundsPerSecond => As(MassFlowUnit.PoundPerSecond);

        /// <summary>
        ///     Get MassFlow in ShortTonsPerHour.
        /// </summary>
        public decimal ShortTonsPerHour => As(MassFlowUnit.ShortTonPerHour);

        /// <summary>
        ///     Get MassFlow in TonnesPerDay.
        /// </summary>
        public decimal TonnesPerDay => As(MassFlowUnit.TonnePerDay);

        /// <summary>
        ///     Get MassFlow in TonnesPerHour.
        /// </summary>
        public decimal TonnesPerHour => As(MassFlowUnit.TonnePerHour);

        #endregion

        #region Static Methods

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        public static string GetAbbreviation(MassFlowUnit unit)
        {
            return GetAbbreviation(unit, null);
        }

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        /// <param name="provider">Format to use for localization. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        public static string GetAbbreviation(MassFlowUnit unit, IFormatProvider? provider)
        {
            return UnitAbbreviationsCache.Default.GetDefaultAbbreviation(unit, provider);
        }

        #endregion

        #region Static Factory Methods

        /// <summary>
        ///     Get MassFlow from CentigramsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromCentigramsPerDay(QuantityValue centigramsperday)
        {
            decimal value = (decimal) centigramsperday;
            return new MassFlow(value, MassFlowUnit.CentigramPerDay);
        }
        /// <summary>
        ///     Get MassFlow from CentigramsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromCentigramsPerSecond(QuantityValue centigramspersecond)
        {
            decimal value = (decimal) centigramspersecond;
            return new MassFlow(value, MassFlowUnit.CentigramPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from DecagramsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromDecagramsPerDay(QuantityValue decagramsperday)
        {
            decimal value = (decimal) decagramsperday;
            return new MassFlow(value, MassFlowUnit.DecagramPerDay);
        }
        /// <summary>
        ///     Get MassFlow from DecagramsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromDecagramsPerSecond(QuantityValue decagramspersecond)
        {
            decimal value = (decimal) decagramspersecond;
            return new MassFlow(value, MassFlowUnit.DecagramPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from DecigramsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromDecigramsPerDay(QuantityValue decigramsperday)
        {
            decimal value = (decimal) decigramsperday;
            return new MassFlow(value, MassFlowUnit.DecigramPerDay);
        }
        /// <summary>
        ///     Get MassFlow from DecigramsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromDecigramsPerSecond(QuantityValue decigramspersecond)
        {
            decimal value = (decimal) decigramspersecond;
            return new MassFlow(value, MassFlowUnit.DecigramPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from GramsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromGramsPerDay(QuantityValue gramsperday)
        {
            decimal value = (decimal) gramsperday;
            return new MassFlow(value, MassFlowUnit.GramPerDay);
        }
        /// <summary>
        ///     Get MassFlow from GramsPerHour.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromGramsPerHour(QuantityValue gramsperhour)
        {
            decimal value = (decimal) gramsperhour;
            return new MassFlow(value, MassFlowUnit.GramPerHour);
        }
        /// <summary>
        ///     Get MassFlow from GramsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromGramsPerSecond(QuantityValue gramspersecond)
        {
            decimal value = (decimal) gramspersecond;
            return new MassFlow(value, MassFlowUnit.GramPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from HectogramsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromHectogramsPerDay(QuantityValue hectogramsperday)
        {
            decimal value = (decimal) hectogramsperday;
            return new MassFlow(value, MassFlowUnit.HectogramPerDay);
        }
        /// <summary>
        ///     Get MassFlow from HectogramsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromHectogramsPerSecond(QuantityValue hectogramspersecond)
        {
            decimal value = (decimal) hectogramspersecond;
            return new MassFlow(value, MassFlowUnit.HectogramPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from KilogramsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromKilogramsPerDay(QuantityValue kilogramsperday)
        {
            decimal value = (decimal) kilogramsperday;
            return new MassFlow(value, MassFlowUnit.KilogramPerDay);
        }
        /// <summary>
        ///     Get MassFlow from KilogramsPerHour.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromKilogramsPerHour(QuantityValue kilogramsperhour)
        {
            decimal value = (decimal) kilogramsperhour;
            return new MassFlow(value, MassFlowUnit.KilogramPerHour);
        }
        /// <summary>
        ///     Get MassFlow from KilogramsPerMinute.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromKilogramsPerMinute(QuantityValue kilogramsperminute)
        {
            decimal value = (decimal) kilogramsperminute;
            return new MassFlow(value, MassFlowUnit.KilogramPerMinute);
        }
        /// <summary>
        ///     Get MassFlow from KilogramsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromKilogramsPerSecond(QuantityValue kilogramspersecond)
        {
            decimal value = (decimal) kilogramspersecond;
            return new MassFlow(value, MassFlowUnit.KilogramPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from MegagramsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromMegagramsPerDay(QuantityValue megagramsperday)
        {
            decimal value = (decimal) megagramsperday;
            return new MassFlow(value, MassFlowUnit.MegagramPerDay);
        }
        /// <summary>
        ///     Get MassFlow from MegapoundsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromMegapoundsPerDay(QuantityValue megapoundsperday)
        {
            decimal value = (decimal) megapoundsperday;
            return new MassFlow(value, MassFlowUnit.MegapoundPerDay);
        }
        /// <summary>
        ///     Get MassFlow from MegapoundsPerHour.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromMegapoundsPerHour(QuantityValue megapoundsperhour)
        {
            decimal value = (decimal) megapoundsperhour;
            return new MassFlow(value, MassFlowUnit.MegapoundPerHour);
        }
        /// <summary>
        ///     Get MassFlow from MegapoundsPerMinute.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromMegapoundsPerMinute(QuantityValue megapoundsperminute)
        {
            decimal value = (decimal) megapoundsperminute;
            return new MassFlow(value, MassFlowUnit.MegapoundPerMinute);
        }
        /// <summary>
        ///     Get MassFlow from MegapoundsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromMegapoundsPerSecond(QuantityValue megapoundspersecond)
        {
            decimal value = (decimal) megapoundspersecond;
            return new MassFlow(value, MassFlowUnit.MegapoundPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from MicrogramsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromMicrogramsPerDay(QuantityValue microgramsperday)
        {
            decimal value = (decimal) microgramsperday;
            return new MassFlow(value, MassFlowUnit.MicrogramPerDay);
        }
        /// <summary>
        ///     Get MassFlow from MicrogramsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromMicrogramsPerSecond(QuantityValue microgramspersecond)
        {
            decimal value = (decimal) microgramspersecond;
            return new MassFlow(value, MassFlowUnit.MicrogramPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from MilligramsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromMilligramsPerDay(QuantityValue milligramsperday)
        {
            decimal value = (decimal) milligramsperday;
            return new MassFlow(value, MassFlowUnit.MilligramPerDay);
        }
        /// <summary>
        ///     Get MassFlow from MilligramsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromMilligramsPerSecond(QuantityValue milligramspersecond)
        {
            decimal value = (decimal) milligramspersecond;
            return new MassFlow(value, MassFlowUnit.MilligramPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from NanogramsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromNanogramsPerDay(QuantityValue nanogramsperday)
        {
            decimal value = (decimal) nanogramsperday;
            return new MassFlow(value, MassFlowUnit.NanogramPerDay);
        }
        /// <summary>
        ///     Get MassFlow from NanogramsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromNanogramsPerSecond(QuantityValue nanogramspersecond)
        {
            decimal value = (decimal) nanogramspersecond;
            return new MassFlow(value, MassFlowUnit.NanogramPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from PoundsPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromPoundsPerDay(QuantityValue poundsperday)
        {
            decimal value = (decimal) poundsperday;
            return new MassFlow(value, MassFlowUnit.PoundPerDay);
        }
        /// <summary>
        ///     Get MassFlow from PoundsPerHour.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromPoundsPerHour(QuantityValue poundsperhour)
        {
            decimal value = (decimal) poundsperhour;
            return new MassFlow(value, MassFlowUnit.PoundPerHour);
        }
        /// <summary>
        ///     Get MassFlow from PoundsPerMinute.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromPoundsPerMinute(QuantityValue poundsperminute)
        {
            decimal value = (decimal) poundsperminute;
            return new MassFlow(value, MassFlowUnit.PoundPerMinute);
        }
        /// <summary>
        ///     Get MassFlow from PoundsPerSecond.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromPoundsPerSecond(QuantityValue poundspersecond)
        {
            decimal value = (decimal) poundspersecond;
            return new MassFlow(value, MassFlowUnit.PoundPerSecond);
        }
        /// <summary>
        ///     Get MassFlow from ShortTonsPerHour.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromShortTonsPerHour(QuantityValue shorttonsperhour)
        {
            decimal value = (decimal) shorttonsperhour;
            return new MassFlow(value, MassFlowUnit.ShortTonPerHour);
        }
        /// <summary>
        ///     Get MassFlow from TonnesPerDay.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromTonnesPerDay(QuantityValue tonnesperday)
        {
            decimal value = (decimal) tonnesperday;
            return new MassFlow(value, MassFlowUnit.TonnePerDay);
        }
        /// <summary>
        ///     Get MassFlow from TonnesPerHour.
        /// </summary>
        /// <exception cref="ArgumentException">If value is NaN or Infinity.</exception>
        public static MassFlow FromTonnesPerHour(QuantityValue tonnesperhour)
        {
            decimal value = (decimal) tonnesperhour;
            return new MassFlow(value, MassFlowUnit.TonnePerHour);
        }

        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="MassFlowUnit" /> to <see cref="MassFlow" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>MassFlow unit value.</returns>
        public static MassFlow From(QuantityValue value, MassFlowUnit fromUnit)
        {
            return new MassFlow((decimal)value, fromUnit);
        }

        #endregion

        #region Static Parse Methods

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        public static MassFlow Parse(string str)
        {
            return Parse(str, null);
        }

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        public static MassFlow Parse(string str, IFormatProvider? provider)
        {
            return QuantityParser.Default.Parse<MassFlow, MassFlowUnit>(
                str,
                provider,
                From);
        }

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        public static bool TryParse(string? str, out MassFlow result)
        {
            return TryParse(str, null, out result);
        }

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        public static bool TryParse(string? str, IFormatProvider? provider, out MassFlow result)
        {
            return QuantityParser.Default.TryParse<MassFlow, MassFlowUnit>(
                str,
                provider,
                From,
                out result);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static MassFlowUnit ParseUnit(string str)
        {
            return ParseUnit(str, null);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static MassFlowUnit ParseUnit(string str, IFormatProvider? provider)
        {
            return UnitParser.Default.Parse<MassFlowUnit>(str, provider);
        }

        /// <inheritdoc cref="TryParseUnit(string,IFormatProvider,out UnitsNet.Units.MassFlowUnit)"/>
        public static bool TryParseUnit(string str, out MassFlowUnit unit)
        {
            return TryParseUnit(str, null, out unit);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="unit">The parsed unit if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.TryParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        public static bool TryParseUnit(string str, IFormatProvider? provider, out MassFlowUnit unit)
        {
            return UnitParser.Default.TryParse<MassFlowUnit>(str, provider, out unit);
        }

        #endregion

        #region Arithmetic Operators

        /// <summary>Negate the value.</summary>
        public static MassFlow operator -(MassFlow right)
        {
            return new MassFlow(-right.Value, right.Unit);
        }

        /// <summary>Get <see cref="MassFlow"/> from adding two <see cref="MassFlow"/>.</summary>
        public static MassFlow operator +(MassFlow left, MassFlow right)
        {
            return new MassFlow(left.Value + right.GetValueAs(left.Unit), left.Unit);
        }

        /// <summary>Get <see cref="MassFlow"/> from subtracting two <see cref="MassFlow"/>.</summary>
        public static MassFlow operator -(MassFlow left, MassFlow right)
        {
            return new MassFlow(left.Value - right.GetValueAs(left.Unit), left.Unit);
        }

        /// <summary>Get <see cref="MassFlow"/> from multiplying value and <see cref="MassFlow"/>.</summary>
        public static MassFlow operator *(decimal left, MassFlow right)
        {
            return new MassFlow(left * right.Value, right.Unit);
        }

        /// <summary>Get <see cref="MassFlow"/> from multiplying value and <see cref="MassFlow"/>.</summary>
        public static MassFlow operator *(MassFlow left, decimal right)
        {
            return new MassFlow(left.Value * right, left.Unit);
        }

        /// <summary>Get <see cref="MassFlow"/> from dividing <see cref="MassFlow"/> by value.</summary>
        public static MassFlow operator /(MassFlow left, decimal right)
        {
            return new MassFlow(left.Value / right, left.Unit);
        }

        /// <summary>Get ratio value from dividing <see cref="MassFlow"/> by <see cref="MassFlow"/>.</summary>
        public static decimal operator /(MassFlow left, MassFlow right)
        {
            return left.GramsPerSecond / right.GramsPerSecond;
        }

        #endregion

        #region Equality / IComparable

        /// <summary>Returns true if less or equal to.</summary>
        public static bool operator <=(MassFlow left, MassFlow right)
        {
            return left.Value <= right.GetValueAs(left.Unit);
        }

        /// <summary>Returns true if greater than or equal to.</summary>
        public static bool operator >=(MassFlow left, MassFlow right)
        {
            return left.Value >= right.GetValueAs(left.Unit);
        }

        /// <summary>Returns true if less than.</summary>
        public static bool operator <(MassFlow left, MassFlow right)
        {
            return left.Value < right.GetValueAs(left.Unit);
        }

        /// <summary>Returns true if greater than.</summary>
        public static bool operator >(MassFlow left, MassFlow right)
        {
            return left.Value > right.GetValueAs(left.Unit);
        }

        /// <summary>Returns true if exactly equal.</summary>
        /// <remarks>Consider using <see cref="Equals(MassFlow, decimal, ComparisonType)"/> for safely comparing floating point values.</remarks>
        public static bool operator ==(MassFlow left, MassFlow right)
        {
            return left.Equals(right);
        }

        /// <summary>Returns true if not exactly equal.</summary>
        /// <remarks>Consider using <see cref="Equals(MassFlow, decimal, ComparisonType)"/> for safely comparing floating point values.</remarks>
        public static bool operator !=(MassFlow left, MassFlow right)
        {
            return !(left == right);
        }

        /// <inheritdoc />
        public int CompareTo(object obj)
        {
            if(obj is null) throw new ArgumentNullException(nameof(obj));
            if(!(obj is MassFlow objMassFlow)) throw new ArgumentException("Expected type MassFlow.", nameof(obj));

            return CompareTo(objMassFlow);
        }

        /// <inheritdoc />
        public int CompareTo(MassFlow other)
        {
            return _value.CompareTo(other.GetValueAs(this.Unit));
        }

        /// <inheritdoc />
        /// <remarks>Consider using <see cref="Equals(MassFlow, decimal, ComparisonType)"/> for safely comparing floating point values.</remarks>
        public override bool Equals(object obj)
        {
            if(obj is null || !(obj is MassFlow objMassFlow))
                return false;

            return Equals(objMassFlow);
        }

        /// <inheritdoc />
        /// <remarks>Consider using <see cref="Equals(MassFlow, decimal, ComparisonType)"/> for safely comparing floating point values.</remarks>
        public bool Equals(MassFlow other)
        {
            return _value.Equals(other.GetValueAs(this.Unit));
        }

        /// <summary>
        ///     <para>
        ///     Compare equality to another MassFlow within the given absolute or relative tolerance.
        ///     </para>
        ///     <para>
        ///     Relative tolerance is defined as the maximum allowable absolute difference between this quantity's value and
        ///     <paramref name="other"/> as a percentage of this quantity's value. <paramref name="other"/> will be converted into
        ///     this quantity's unit for comparison. A relative tolerance of 0.01 means the absolute difference must be within +/- 1% of
        ///     this quantity's value to be considered equal.
        ///     <example>
        ///     In this example, the two quantities will be equal if the value of b is within +/- 1% of a (0.02m or 2cm).
        ///     <code>
        ///     var a = Length.FromMeters(2.0);
        ///     var b = Length.FromInches(50.0);
        ///     a.Equals(b, 0.01, ComparisonType.Relative);
        ///     </code>
        ///     </example>
        ///     </para>
        ///     <para>
        ///     Absolute tolerance is defined as the maximum allowable absolute difference between this quantity's value and
        ///     <paramref name="other"/> as a fixed number in this quantity's unit. <paramref name="other"/> will be converted into
        ///     this quantity's unit for comparison.
        ///     <example>
        ///     In this example, the two quantities will be equal if the value of b is within 0.01 of a (0.01m or 1cm).
        ///     <code>
        ///     var a = Length.FromMeters(2.0);
        ///     var b = Length.FromInches(50.0);
        ///     a.Equals(b, 0.01, ComparisonType.Absolute);
        ///     </code>
        ///     </example>
        ///     </para>
        ///     <para>
        ///     Note that it is advised against specifying zero difference, due to the nature
        ///     of floating point operations and using System.Double internally.
        ///     </para>
        /// </summary>
        /// <param name="other">The other quantity to compare to.</param>
        /// <param name="tolerance">The absolute or relative tolerance value. Must be greater than or equal to 0.</param>
        /// <param name="comparisonType">The comparison type: either relative or absolute.</param>
        /// <returns>True if the absolute difference between the two values is not greater than the specified relative or absolute tolerance.</returns>
        public bool Equals(MassFlow other, decimal tolerance, ComparisonType comparisonType)
        {
            if(tolerance < 0)
                throw new ArgumentOutOfRangeException("tolerance", "Tolerance must be greater than or equal to 0.");

            decimal thisValue = (decimal)this.Value;
            decimal otherValueInThisUnits = other.As(this.Unit);

            return UnitsNet.Comparison.Equals(thisValue, otherValueInThisUnits, tolerance, comparisonType);
        }

        /// <summary>
        ///     Returns the hash code for this instance.
        /// </summary>
        /// <returns>A hash code for the current MassFlow.</returns>
        public override int GetHashCode()
        {
            return new { QuantityType, Value, Unit }.GetHashCode();
        }

        #endregion

        #region Conversion Methods

        /// <summary>
        ///     Convert to the unit representation <paramref name="unit" />.
        /// </summary>
        /// <returns>Value converted to the specified unit.</returns>
        public decimal As(MassFlowUnit unit)
        {
            if(Unit == unit)
                return Convert.ToDecimal(Value);

            var converted = GetValueAs(unit);
            return Convert.ToDecimal(converted);
        }

        /// <inheritdoc cref="IQuantity.As(UnitSystem)"/>
        public decimal As(UnitSystem unitSystem)
        {
            if(unitSystem is null)
                throw new ArgumentNullException(nameof(unitSystem));

            var unitInfos = Info.GetUnitInfosFor(unitSystem.BaseUnits);

            var firstUnitInfo = unitInfos.FirstOrDefault();
            if(firstUnitInfo == null)
                throw new ArgumentException("No units were found for the given UnitSystem.", nameof(unitSystem));

            return As(firstUnitInfo.Value);
        }

        /// <inheritdoc />
        decimal IQuantity.As(Enum unit)
        {
            if(!(unit is MassFlowUnit unitAsMassFlowUnit))
                throw new ArgumentException($"The given unit is of type {unit.GetType()}. Only {typeof(MassFlowUnit)} is supported.", nameof(unit));

            return As(unitAsMassFlowUnit);
        }

        /// <summary>
        ///     Converts this MassFlow to another MassFlow with the unit representation <paramref name="unit" />.
        /// </summary>
        /// <returns>A MassFlow with the specified unit.</returns>
        public MassFlow ToUnit(MassFlowUnit unit)
        {
            var convertedValue = GetValueAs(unit);
            return new MassFlow(convertedValue, unit);
        }

        /// <inheritdoc />
        IQuantity IQuantity.ToUnit(Enum unit)
        {
            if(!(unit is MassFlowUnit unitAsMassFlowUnit))
                throw new ArgumentException($"The given unit is of type {unit.GetType()}. Only {typeof(MassFlowUnit)} is supported.", nameof(unit));

            return ToUnit(unitAsMassFlowUnit);
        }

        /// <inheritdoc cref="IQuantity.ToUnit(UnitSystem)"/>
        public MassFlow ToUnit(UnitSystem unitSystem)
        {
            if(unitSystem is null)
                throw new ArgumentNullException(nameof(unitSystem));

            var unitInfos = Info.GetUnitInfosFor(unitSystem.BaseUnits);

            var firstUnitInfo = unitInfos.FirstOrDefault();
            if(firstUnitInfo == null)
                throw new ArgumentException("No units were found for the given UnitSystem.", nameof(unitSystem));

            return ToUnit(firstUnitInfo.Value);
        }

        /// <inheritdoc />
        IQuantity IQuantity.ToUnit(UnitSystem unitSystem) => ToUnit(unitSystem);

        /// <inheritdoc />
        IQuantity<MassFlowUnit> IQuantity<MassFlowUnit>.ToUnit(MassFlowUnit unit) => ToUnit(unit);

        /// <inheritdoc />
        IQuantity<MassFlowUnit> IQuantity<MassFlowUnit>.ToUnit(UnitSystem unitSystem) => ToUnit(unitSystem);

        /// <summary>
        ///     Converts the current value + unit to the base unit.
        ///     This is typically the first step in converting from one unit to another.
        /// </summary>
        /// <returns>The value in the base unit representation.</returns>
        private decimal GetValueInBaseUnit()
        {
            switch(Unit)
            {
                case MassFlowUnit.CentigramPerDay: return (_value/86400m) * 1e-2m;
                case MassFlowUnit.CentigramPerSecond: return (_value) * 1e-2m;
                case MassFlowUnit.DecagramPerDay: return (_value/86400m) * 1e1m;
                case MassFlowUnit.DecagramPerSecond: return (_value) * 1e1m;
                case MassFlowUnit.DecigramPerDay: return (_value/86400m) * 1e-1m;
                case MassFlowUnit.DecigramPerSecond: return (_value) * 1e-1m;
                case MassFlowUnit.GramPerDay: return _value/86400m;
                case MassFlowUnit.GramPerHour: return _value/3600m;
                case MassFlowUnit.GramPerSecond: return _value;
                case MassFlowUnit.HectogramPerDay: return (_value/86400m) * 1e2m;
                case MassFlowUnit.HectogramPerSecond: return (_value) * 1e2m;
                case MassFlowUnit.KilogramPerDay: return (_value/86400m) * 1e3m;
                case MassFlowUnit.KilogramPerHour: return _value/3.6m;
                case MassFlowUnit.KilogramPerMinute: return _value/0.06m;
                case MassFlowUnit.KilogramPerSecond: return (_value) * 1e3m;
                case MassFlowUnit.MegagramPerDay: return (_value/86400m) * 1e6m;
                case MassFlowUnit.MegapoundPerDay: return (_value/190.47936m) * 1e6m;
                case MassFlowUnit.MegapoundPerHour: return (_value/7.93664m) * 1e6m;
                case MassFlowUnit.MegapoundPerMinute: return (_value/0.132277m) * 1e6m;
                case MassFlowUnit.MegapoundPerSecond: return (_value * 453.59237m) * 1e6m;
                case MassFlowUnit.MicrogramPerDay: return (_value/86400m) * 1e-6m;
                case MassFlowUnit.MicrogramPerSecond: return (_value) * 1e-6m;
                case MassFlowUnit.MilligramPerDay: return (_value/86400m) * 1e-3m;
                case MassFlowUnit.MilligramPerSecond: return (_value) * 1e-3m;
                case MassFlowUnit.NanogramPerDay: return (_value/86400m) * 1e-9m;
                case MassFlowUnit.NanogramPerSecond: return (_value) * 1e-9m;
                case MassFlowUnit.PoundPerDay: return _value/190.47936m;
                case MassFlowUnit.PoundPerHour: return _value/7.93664m;
                case MassFlowUnit.PoundPerMinute: return _value/0.132277m;
                case MassFlowUnit.PoundPerSecond: return _value * 453.59237m;
                case MassFlowUnit.ShortTonPerHour: return _value*251.9957611m;
                case MassFlowUnit.TonnePerDay: return _value/0.0864000m;
                case MassFlowUnit.TonnePerHour: return 1000m*_value/3.6m;
                default:
                    throw new NotImplementedException($"Can not convert {Unit} to base units.");
            }
        }

        /// <summary>
        ///     Converts the current value + unit to the base unit.
        ///     This is typically the first step in converting from one unit to another.
        /// </summary>
        /// <returns>The value in the base unit representation.</returns>
        internal MassFlow ToBaseUnit()
        {
            var baseUnitValue = GetValueInBaseUnit();
            return new MassFlow(baseUnitValue, BaseUnit);
        }

        private decimal GetValueAs(MassFlowUnit unit)
        {
            if(Unit == unit)
                return _value;

            var baseUnitValue = GetValueInBaseUnit();

            switch(unit)
            {
                case MassFlowUnit.CentigramPerDay: return (baseUnitValue*86400m) / 1e-2m;
                case MassFlowUnit.CentigramPerSecond: return (baseUnitValue) / 1e-2m;
                case MassFlowUnit.DecagramPerDay: return (baseUnitValue*86400m) / 1e1m;
                case MassFlowUnit.DecagramPerSecond: return (baseUnitValue) / 1e1m;
                case MassFlowUnit.DecigramPerDay: return (baseUnitValue*86400m) / 1e-1m;
                case MassFlowUnit.DecigramPerSecond: return (baseUnitValue) / 1e-1m;
                case MassFlowUnit.GramPerDay: return baseUnitValue*86400m;
                case MassFlowUnit.GramPerHour: return baseUnitValue*3600m;
                case MassFlowUnit.GramPerSecond: return baseUnitValue;
                case MassFlowUnit.HectogramPerDay: return (baseUnitValue*86400m) / 1e2m;
                case MassFlowUnit.HectogramPerSecond: return (baseUnitValue) / 1e2m;
                case MassFlowUnit.KilogramPerDay: return (baseUnitValue*86400m) / 1e3m;
                case MassFlowUnit.KilogramPerHour: return baseUnitValue*3.6m;
                case MassFlowUnit.KilogramPerMinute: return baseUnitValue*0.06m;
                case MassFlowUnit.KilogramPerSecond: return (baseUnitValue) / 1e3m;
                case MassFlowUnit.MegagramPerDay: return (baseUnitValue*86400m) / 1e6m;
                case MassFlowUnit.MegapoundPerDay: return (baseUnitValue*190.47936m) / 1e6m;
                case MassFlowUnit.MegapoundPerHour: return (baseUnitValue*7.93664m) / 1e6m;
                case MassFlowUnit.MegapoundPerMinute: return (baseUnitValue*0.132277m) / 1e6m;
                case MassFlowUnit.MegapoundPerSecond: return (baseUnitValue / 453.59237m) / 1e6m;
                case MassFlowUnit.MicrogramPerDay: return (baseUnitValue*86400m) / 1e-6m;
                case MassFlowUnit.MicrogramPerSecond: return (baseUnitValue) / 1e-6m;
                case MassFlowUnit.MilligramPerDay: return (baseUnitValue*86400m) / 1e-3m;
                case MassFlowUnit.MilligramPerSecond: return (baseUnitValue) / 1e-3m;
                case MassFlowUnit.NanogramPerDay: return (baseUnitValue*86400m) / 1e-9m;
                case MassFlowUnit.NanogramPerSecond: return (baseUnitValue) / 1e-9m;
                case MassFlowUnit.PoundPerDay: return baseUnitValue*190.47936m;
                case MassFlowUnit.PoundPerHour: return baseUnitValue*7.93664m;
                case MassFlowUnit.PoundPerMinute: return baseUnitValue*0.132277m;
                case MassFlowUnit.PoundPerSecond: return baseUnitValue / 453.59237m;
                case MassFlowUnit.ShortTonPerHour: return baseUnitValue/251.9957611m;
                case MassFlowUnit.TonnePerDay: return baseUnitValue*0.0864000m;
                case MassFlowUnit.TonnePerHour: return baseUnitValue*3.6m/1000m;
                default:
                    throw new NotImplementedException($"Can not convert {Unit} to {unit}.");
            }
        }

        #endregion

        #region ToString Methods

        /// <summary>
        ///     Gets the default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
        {
            return ToString("g");
        }

        /// <summary>
        ///     Gets the default string representation of value and unit using the given format provider.
        /// </summary>
        /// <returns>String representation.</returns>
        /// <param name="provider">Format to use for localization and number formatting. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        public string ToString(IFormatProvider? provider)
        {
            return ToString("g", provider);
        }

        /// <summary>
        ///     Get string representation of value and unit.
        /// </summary>
        /// <param name="significantDigitsAfterRadix">The number of significant digits after the radix point.</param>
        /// <returns>String representation.</returns>
        /// <param name="provider">Format to use for localization and number formatting. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        [Obsolete(@"This method is deprecated and will be removed at a future release. Please use ToString(""s2"") or ToString(""s2"", provider) where 2 is an example of the number passed to significantDigitsAfterRadix.")]
        public string ToString(IFormatProvider? provider, int significantDigitsAfterRadix)
        {
            var value = Convert.ToDecimal(Value);
            var format = UnitFormatter.GetFormat(value, significantDigitsAfterRadix);
            return ToString(provider, format);
        }

        /// <summary>
        ///     Get string representation of value and unit.
        /// </summary>
        /// <param name="format">String format to use. Default:  "{0:0.##} {1} for value and unit abbreviation respectively."</param>
        /// <param name="args">Arguments for string format. Value and unit are implicitly included as arguments 0 and 1.</param>
        /// <returns>String representation.</returns>
        /// <param name="provider">Format to use for localization and number formatting. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        [Obsolete("This method is deprecated and will be removed at a future release. Please use string.Format().")]
        public string ToString(IFormatProvider? provider, [NotNull] string format, [NotNull] params object[] args)
        {
            if (format == null) throw new ArgumentNullException(nameof(format));
            if (args == null) throw new ArgumentNullException(nameof(args));

            provider = provider ?? CultureInfo.CurrentUICulture;

            var value = Convert.ToDecimal(Value);
            var formatArgs = UnitFormatter.GetFormatArgs(Unit, value, provider, args);
            return string.Format(provider, format, formatArgs);
        }

        /// <inheritdoc cref="QuantityFormatter.Format{TUnitType}(IQuantity{TUnitType}, string, IFormatProvider)"/>
        /// <summary>
        /// Gets the string representation of this instance in the specified format string using <see cref="CultureInfo.CurrentUICulture" />.
        /// </summary>
        /// <param name="format">The format string.</param>
        /// <returns>The string representation.</returns>
        public string ToString(string format)
        {
            return ToString(format, CultureInfo.CurrentUICulture);
        }

        /// <inheritdoc cref="QuantityFormatter.Format{TUnitType}(IQuantity{TUnitType}, string, IFormatProvider)"/>
        /// <summary>
        /// Gets the string representation of this instance in the specified format string using the specified format provider, or <see cref="CultureInfo.CurrentUICulture" /> if null.
        /// </summary>
        /// <param name="format">The format string.</param>
        /// <param name="provider">Format to use for localization and number formatting. Defaults to <see cref="CultureInfo.CurrentUICulture" /> if null.</param>
        /// <returns>The string representation.</returns>
        public string ToString(string format, IFormatProvider? provider)
        {
            return QuantityFormatter.Format<MassFlowUnit>(this, format, provider);
        }

        #endregion

        #region IConvertible Methods

        TypeCode IConvertible.GetTypeCode()
        {
            return TypeCode.Object;
        }

        bool IConvertible.ToBoolean(IFormatProvider provider)
        {
            throw new InvalidCastException($"Converting {typeof(MassFlow)} to bool is not supported.");
        }

        byte IConvertible.ToByte(IFormatProvider provider)
        {
            return Convert.ToByte(_value);
        }

        char IConvertible.ToChar(IFormatProvider provider)
        {
            throw new InvalidCastException($"Converting {typeof(MassFlow)} to char is not supported.");
        }

        DateTime IConvertible.ToDateTime(IFormatProvider provider)
        {
            throw new InvalidCastException($"Converting {typeof(MassFlow)} to DateTime is not supported.");
        }

        decimal IConvertible.ToDecimal(IFormatProvider provider)
        {
            return Convert.ToDecimal(_value);
        }

        double IConvertible.ToDouble(IFormatProvider provider)
        {
            return Convert.ToDouble(_value);
        }

        short IConvertible.ToInt16(IFormatProvider provider)
        {
            return Convert.ToInt16(_value);
        }

        int IConvertible.ToInt32(IFormatProvider provider)
        {
            return Convert.ToInt32(_value);
        }

        long IConvertible.ToInt64(IFormatProvider provider)
        {
            return Convert.ToInt64(_value);
        }

        sbyte IConvertible.ToSByte(IFormatProvider provider)
        {
            return Convert.ToSByte(_value);
        }

        float IConvertible.ToSingle(IFormatProvider provider)
        {
            return Convert.ToSingle(_value);
        }

        string IConvertible.ToString(IFormatProvider provider)
        {
            return ToString("g", provider);
        }

        object IConvertible.ToType(Type conversionType, IFormatProvider provider)
        {
            if(conversionType == typeof(MassFlow))
                return this;
            else if(conversionType == typeof(MassFlowUnit))
                return Unit;
            else if(conversionType == typeof(QuantityType))
                return MassFlow.QuantityType;
            else if(conversionType == typeof(BaseDimensions))
                return MassFlow.BaseDimensions;
            else
                throw new InvalidCastException($"Converting {typeof(MassFlow)} to {conversionType} is not supported.");
        }

        ushort IConvertible.ToUInt16(IFormatProvider provider)
        {
            return Convert.ToUInt16(_value);
        }

        uint IConvertible.ToUInt32(IFormatProvider provider)
        {
            return Convert.ToUInt32(_value);
        }

        ulong IConvertible.ToUInt64(IFormatProvider provider)
        {
            return Convert.ToUInt64(_value);
        }

        #endregion
    }
}
